# Generated by Django 5.0 on 2024-01-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='like_count',
        ),
    ]
